uac:
  type: static
  users:
    - user_id: abcdef
      permissions:
        - render_pdf

auth:
  type: jwt-jwk
  jwkUrl: https://login.manga-datenbank.de/realms/VB3D-Dev/protocol/openid-connect/certs
